site_name: Work笔记本
site_author: wz1qqx
site_url: https://wz1qqx.github.io/

# Repository
repo_name: wz1qqx/wz1qqx.github.io
repo_url: https://github.com/wz1qqx/wz1qqx.github.io/

# Copyright
copyright: "Copyright &copy; 2023 - 2023 Zq"

theme: 
  name: 'material'
  language: 'zh'
  font: false
  palette:
    - scheme: default

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - codehilite:
      guess_lang: false
      linenums: false
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true

# extra:
#   social:
#     - type: 'github'
#       link: 'https://github.com/wz1qqx'

nav:
  - Home:
    - index.md
  - ML Framework:
    - ML FrameWork/xacc.md